apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dapr.io/app-id: web-server
    dapr.io/app-port: '8080'
    dapr.io/config: dapr-config
    dapr.io/enable-api-logging: 'true'
    dapr.io/enabled: 'true'
  labels:
    app: web-server
  name: web-server
  namespace: dev
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2025-04-23T14:33:58Z'
        dapr.io/app-id: web-server
        dapr.io/app-port: '8080'
        dapr.io/config: dapr-config
        dapr.io/enable-api-logging: 'true'
        dapr.io/enabled: 'true'
      labels:
        app: web-server
    spec:
      containers:
        - 
          image: docker.cnb.cool/ercjul/daprProxyExamples/webserver:latest
          imagePullPolicy: Always
          name: web-server
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 180